---

- block:
    - name: Configure postgresql repository key
      apt_key:
        url: "{{ postgresql_apt_key_url }}"
      when: postgresql_apt_key_url != ""

    - name: Configure postgresql repository
      apt_repository:
        repo: "{{ postgresql_apt_repo }}"
        filename: "{{ postgresql_apt_filename }}"

    - name: Ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        update_cache: yes

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "Debian"

- block:
    - name: "Configure postgresql repository key"
      rpm_key:
        state: present
        key: "{{ postgresql_yum_repo_gpg_key_url }}"
      when: patroni_install_postgresql_repo | bool

    - name: Configure postgresql repository
      package:
        name: "{{ postgresql_yum_repo_url }}"
      when: patroni_install_postgresql_repo | bool

    - name: Disable postgresql module
      command: "dnf -y module disable postgresql"
      changed_when: false
      when: ansible_distribution_major_version >= "8"
  when: ansible_os_family == "RedHat"

- name: Install postgresql packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_postgresql_packages }}"
