---

- name: Add patroni group
  group:
    name: "{{ patroni_system_group }}"
    state: present

- name: Add patroni user
  user:
    name: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    system: yes
