---

- name: Install watchdog
  package:
    name: watchdog
    update_cache: yes

- name: Make kernel watchdog device available for patroni
  template:
    src: patroni-watchdog.service.j2
    dest: /etc/systemd/system/patroni-watchdog.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart patroni-watchdog

# Dirty hack. See https://bugs.launchpad.net/ubuntu/+source/watchdog/+bug/1448924
- name: Enable watchdog daemon to start on boot
  file:
    src: /lib/systemd/system/watchdog.service
    dest: /etc/systemd/system/multi-user.target.wants/watchdog.service
    state: link
  when: ansible_distribution in ('Ubuntu', 'Debian') and 
        ansible_distribution_release in ('xenial', 'jessie')
